routes/web.php
<?php

use App\Account;
use App\Business;
use App\Invoice;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('homepage');
Route::get('/old', 'PagesController@oldindex')->name('oldhomepage');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/pricing', 'PagesController@pricing')->name('pricing');
Route::resource('contactus', 'ContactusController');

// Errors ROute
Route::get('/404', function() {
	return view('dashboard.404_page');
})->name('404');


Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/new_plan', 'SubscriptionPlanController@store')->name('plan');

Route::get('users_list', 'UsersController@UsersList');
Route::post('/new_accounts', 'AccountsController@store')->name('accounts');

Route::resource('subscription_plan', 'SubscriptionPlanController');
Route::resource('business', 'BusinessController');
Route::resource('subscribe', 'SubscribersController');
Route::resource('accounts', 'AccountsController');

Route::group(['prefix'=>'{businessCode}', 'middleware'=>['businessMiddleware']],function($businessCode){
	Route::resource('dashboard', 'DashboardController');
	// Route::resource('businessaccounts', 'BusinessAccountsController');
	Route::resource('chartofaccounts', 'ChartOfAccountsController');
	Route::resource('journal', 'JournalController')->middleware('CheckSubscription');
	Route::resource('users', 'UsersController')->middleware(['CheckSubscription', 'Subscription']);

	Route::resource('userbusiness', 'UserBusinessController');
	// Route::get('12mcashflow', 'CashFlowController@months12');
	Route::resource('invoice', 'InvoiceController');
	Route::resource('customers', 'CustomerController');
	Route::resource('items', 'ItemController');

	/**
	 * Reporting Routes
	 */
	Route::resource('income_statement', 'IncomeStatementController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('cashflow', 'CashFlowController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('balance_sheet', 'BalanceSheetController')->middleware(['CheckSubscription', 'Subscription']);
	/**
	 * Get reporting details route
	 */
	Route::post('getbalancesheet', 'BalanceSheetController@getBalancesheet')->name('getBS');
	Route::post('getcashflow', 'CashFlowController@getCashFlow')->name('getCF');
	Route::post('items.price', 'ItemController@showPrice')->name('getPrice');

	Route::get('income-generate-pdf/{start_date}/{end_date}','IncomeStatementController@generatePDF')->name('income-generate-pdf');
	Route::get('balance-generate-pdf/{start_date}/{end_date}','BalanceSheetController@generatePDF')->name('balance-generate-pdf');
	Route::get('cashflow-generate-pdf/{start_date}/{end_date}','CashFlowController@generatePDF')->name('cashflow-generate-pdf');
	Route::get('download-pdf/{id}','InvoiceController@downloadInvoiceasPDF')->name('download-pdf');

});




Route::get('/industries/{account_id}', function ($account_id) {
	$account = Account::where('id','=',$account_id)->first();

	return $account->accounttype->name;
	// $json = asset('static/industries.json');
 //    return $json;
});

//Paystack route
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay'); 
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

Route::get('export','IncomeStatementController@export')->name('export');


Route::get('mailable/{businesscode}/{id}', function ($businessCode,$id) {
	$business = Business::where(['business_code'=>$businessCode])->first();
	$invoice = Invoice::where(['id'=>$id,'business_id'=>$business->id])->first();
	if($invoice){
		return new App\Mail\InvoiceMail($invoice);
	}else {
		return view('dashboard.404_page');
	}
})->name('mailable');

// Route::get('/play', function() {

// 	$j =  Invoice::generateInvoiceCode();
// 	return $j;
// });

Route::get('/bela', function() {
	return view('dashboard.pdf.cashflow_dataPDF');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Business;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($businessCode)
    {
        // Route::current()->parameter('id');
        $businesses = DB::table('businesses')
                    ->leftJoin('user_businesses', 'businesses.id', '=', 'user_businesses.business_id')
                    ->where('user_businesses.user_id', '=', auth()->user()->id)
                    ->select('businesses.*')
                    ->orderBy('businesses.id','asc')
                    ->get();
        $businessInfo = DB::table('businesses')
                        ->where('businesses.business_code', '=', $businessCode)
                        ->first();
        $customers = DB::table('customers')
                        ->where('customers.business_id', '=', $businessInfo->id)
                        ->select('customers.*')
                        ->get();
        $items =  DB::table('items')
                        ->where('items.business_id', '=', $businessInfo->id)
                        ->leftJoin('accounts', 'items.account_id', '=', 'accounts.id')
                        ->select('items.*','accounts.account_name')
                        ->get();
        $invoices =  DB::table('invoices')
                        ->where('invoices.business_id', '=', $businessInfo->id)
                        ->select('invoices.*')
                        ->get();
        $transactions =  DB::table('transactions')
                        ->where('transactions.business_id', '=', $businessInfo->id)
                        ->select('transactions.*')
                        ->get();
        $cash_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 1)
                        ->select('client_ledger.*')
                        ->get();
        $all_cash_balances = array_pluck($cash_ledger, 'balance');
        $last_cash = last($all_cash_balances);

        $sales_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 14)
                        ->select('client_ledger.*')
                        ->get();

        $service_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 15)
                        ->select('client_ledger.*')
                        ->get();
        // return count($sales_revenue_ledger);
        if(count($sales_revenue_ledger) > 0)
        {
            $all_revenue_balances = array_pluck($sales_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);
        }
        else {
            $all_revenue_balances = array_pluck($service_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);  
        }
        return view('dashboard.dashboard', compact('businesses', 'businessInfo','customers','items',
        'invoices','transactions','last_cash','last_revenue'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\Account;
use App\Journal;
use App\Transaction;
use App\ClientLedger;

use App\Invoice;
use App\InvoiceTransaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use App\Mail\InvoiceMail1;
use Illuminate\Support\Facades\Mail;
use PDF;

use App\Http\Traits\LedgerTrait;
use App\Http\Traits\JournalTrait;
use App\Http\Traits\BusinessTrait;

class InvoiceController extends Controller
{
    use LedgerTrait, JournalTrait, BusinessTrait;
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($businessCode)
    {
        $businesses = $this->userBusinessList();

        $businessInfo = $this->businessInfo($businessCode);
         
        $invoices = Invoice::where('business_id', $businessInfo->id)->orderBy("id","desc")->get();

        return view('dashboard.invoice.invoice', compact('businesses', 'businessInfo','invoices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($businessCode)
    {
        $businesses = $this->userBusinessList();

        $businessInfo = $this->businessInfo($businessCode);

        $customers = DB::table('customers')
                    ->where('customers.business_id', '=', $businessInfo->id)
                    ->select('customers.*')
                    ->get();
        $items =  DB::table('items')
                    ->where('items.business_id', '=', $businessInfo->id)
                    ->leftJoin('accounts', 'items.account_id', '=', 'accounts.id')
                    ->select('items.*','accounts.account_name')
                    ->get();

        return view('dashboard.invoice.invoice-create', compact('businesses','businessInfo', 'customers','items'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($businessCode, Request $request)
    {
        // return $request;
        $business = DB::table('businesses')
        ->where('businesses.business_code', '=', $businessCode)
        ->first();

        $rules = [
        'customer_id' => 'required',
        'invoice_date' => 'required'
        ];

        $this->validate($request, $rules);

        $data = $request->all();
        $data['user_id'] = auth()->user()->id;
        $data['business_id'] = $business->id;
        $data['invoice_no'] = Invoice::generateInvoiceCode();
        if($request->discount == ''){
            $data['discount'] = '0';
        }else {
            $data['discount'] = $request->discount;
        }
        if($request->vat == ''){
            $data['vat'] = '0';
        }else {
            $data['vat'] = $request->vat;
        }

        $invoice = Invoice::create($data);
      
        if($invoice){
            for($i=0; $i < count($request->item); $i++){
                self::invoiceTransaction($invoice->id, $request->item[$i], $request->item_description[$i], 
                $request->quantity[$i], $request->unit_cost[$i],$business);
            }
          }

        // retry(5, function() use ($invoice){
        //     Mail::to($invoice->customer->email)->send(new InvoiceMail1($invoice));
        // }, 100);
        $success = "New Invoice Created";
        
        $invoice_view_url = route('invoice.show', ['businessCode' => $businessCode, 'invoice' => $invoice->id]);
        
        return response()->json([$success,$invoice_view_url]);
    }

    public function invoiceTransaction($invoice_id, $item_id, $description, $quantity, $unit_cost, $business)
    {
            $data['invoice_id'] = $invoice_id;
            $data['item_id'] = $item_id;
            $data['description'] = $description;
            $data['quantity'] = $quantity;
            $data['unit_cost'] = $unit_cost;
            $invoiceTransaction = InvoiceTransaction::create($data);
            self::logJournalEntry($business, $item_id,  $quantity, $unit_cost, $description);
    }

    public function logJournalEntry($business, $item_id, $quantity, $unit_cost, $description)
    {
        $amount = $quantity * $unit_cost;
        $item_account_id = Item::where('id','=',$item_id)->pluck('account_id')[0];  // Credit
        $account_receiveable_id = Account::where('account_name','=','Accounts receivable')->pluck('id')[0];  // Debit

        // $data = [];
        $data['user_id'] = auth()->user()->id;
        $data['description'] = $description;
        $data['business_id'] = $business->id;

        $transaction = Transaction::create($data);

        $this->debitTransactionJournal($transaction->id, $account_receiveable_id, $amount);
        $this->creditTransactionJournal($transaction->id, $item_account_id, $amount);

        $this->debitLedger($business->id, $account_receiveable_id, $amount);
        $this->creditLedger($business->id, $item_account_id, $amount);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function show($businessCode, $id)
    {
        $businesses = $this->userBusinessList();

        $businessInfo = $this->businessInfo($businessCode);

        $invoice = Invoice::where(['id'=>$id, 'user_id'=>auth()->user()->id])->with('invoicetransaction')->with('customer')->first();

        if($invoice) {
            return view('dashboard.invoice.invoice-view', compact('businesses', 'businessInfo','invoice'));
        }else {
            return view('dashboard.404_page');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function edit(Invoice $invoice)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Invoice $invoice)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Invoice $invoice)
    {
        //
    }

          /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function downloadInvoiceasPDF($businessCode, $id)
    {
        $businessInfo = DB::table('businesses')
                        ->where('businesses.business_code', '=', $businessCode)
                        ->first();
        $invoice = Invoice::where('id', $id)->with('invoicetransaction')->with('customer')->first();

        $subtotal = [];

        foreach ($invoice->invoicetransaction as $key => $value) {
           array_push($subtotal, $value->quantity * $value->unit_cost);
        }
        $subtotal = array_sum($subtotal);
        $discount = $this->calculateDiscount($invoice->discount, $subtotal);
        // total sum for subtotal and discount 
        $total_sum = $subtotal - $discount;

        $vat = $this->calculateVat($invoice->vat, $total_sum);
        // return $vat;
        
        $data = ['title' => 'Welcome to HDTuto.com','businessInfo'=>$businessInfo, 
                'invoice'=>$invoice, 'subtotal'=>$subtotal, 'discount'=>$discount, 'vat'=>$vat];

        $pdf = PDF::loadView('dashboard.pdf.invoicePDF', $data);
  
        return $pdf->download('invoice');
    }

    public function calculateDiscount($discount, $subtotal)
    {
        if($discount > 0){
            $discount = ($discount * $subtotal) / 100;
        }else {
            $discount = 0.0;
        }
        return $discount;
    }

    public function calculateVat($vat, $total_sum)
    {
        if($vat > 0){
            $vat = ($vat * $total_sum) / 100;
        }else {
            $vat = 0.0;
        }
        return $vat;
    }
}

resources/views/dashboard/invoice/invoice-create.blade.php
@extends('dashboard.invoice.invoice_template')

@section('invoice-breadcrumb')
<li class="breadcrumb-item active">New Invoice</li>
@endsection

@section('page-title')
  New Invoice
@endsection

@section('view-style')
  <style>
    @media only screen and (max-width: 600px) {
      .cost {
        width: 90px;
      }
      .item {
        width: 90px;
      }
    }
  </style>
@endsection


@section('invoice-inbox')
<main>
  <div class="toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-light">
        <b>
          <span class="icon-note"></span> Create
        </b>
      </button>
    </div>
    <div class="btn-group">
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#addModal">
          <span class="fa fa-plus"></span> New Invoice
        </button>
      </div>
  </div>
  <form id="user_form" method="post">
  <div class="form-group row">
      <label class="col-md-3 col-form-label" for="customer">Customer Name</label>
      <div class="col-md-9">
        <select class="form-control" id="customer" name="customer_id">
            @if($customers->count() > 0)
              @foreach($customers as $customer)
              <option value="{{$customer->id}}">{{$customer->first_name}} {{$customer->last_name}}</option>
              @endforeach
            @endif
        </select>
      </div>
    </div>
  {{-- <div class="form-group row">
      <label class="col-md-3 col-form-label" for="invoice_no">Invoice#</label>
      <div class="col-md-9">
        <input type="text" id="invoice_no" name="invoice_no" value="INV-00000" class="form-control" placeholder="Text">
        <span class="help-block">Autogenerate Number Enabled</span>
      </div>
  </div> --}}
    <div class="row">
      <div class="col-sm-6">
          <fieldset class="form-group">
              <label>Invoice Date</label>
              <div class="input-group">
                <span class="input-group-prepend">
                  <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </span>
                <input name="invoice_date" class="form-control" type="text" invoice-date>
              </div>
            </fieldset>
      </div>
      <div class="col-sm-6">
          <fieldset class="form-group">
              <label>Due Date</label>
              <div class="input-group">
                <span class="input-group-prepend">
                  <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </span>
                <input name="due_date" class="form-control" type="text" invoice-date>
              </div>
            </fieldset>
      </div>
    </div>

      <div class="table-responsive-sm">
        <table class="table table-bordered " >
          <thead>
            <tr>
              <th>Item</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Unit Cost</th>
              {{-- <th>Tax Rate</th> --}}
              <th class="bg-light">Amount</th>
              <th class="bg-light">
                <button type="button" class="btn btn-danger btn-sm" remove-row><i class="fa fa-trash-o"></i></button>
              </th>
            </tr>
          </thead>
          <tbody item-list>

          </tbody>
        </table>
      </div>

      <button type="button" class="btn btn-default mb-2 mt-3" @if($items->count() == 0) disabled @endif new-line>Add New Line</button>
      <div class="row">

          <div class="col-lg-4 col-sm-5">
              <textarea id="description" name="description" rows="9" 
              class="form-control" placeholder="Invoice Comment"></textarea>
          </div>
          <!--/.col-->

          @include('dashboard.invoice-template-total')

        </div>
        <!--/.row-->
        <div class="form-group mt-3 text-center">
          <button type="submit" id="send" class="btn btn-success" @if($customers->count() == 0 || $items->count() == 0) disabled @endif>
              <i class="fa fa-send-o"></i> Send</button>
          {{-- <button type="button" class="btn btn-light">
            <i class="fa fa-bookmark"></i> Save as Draft</button> --}}
          <button type="button" onclick="window.history.go(-1)" class="btn btn-danger">
            <i class="fa fa-trash-o"></i> Discard</button>
        </div>
  </form>
    <script>
     $(document).ready( function() {
      // console.log(11)
      
  $('input[invoice-date]').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    minYear: 1901,
    maxYear: parseInt(moment().format('YYYY'),10)
  })
  // $( this ).slideUp(); this remove a particuler click element
  var count = 0;
  var total_sum = 0;
  var discount_sum = 0;
   var dis = 0;
  

  $("[new-line]").click(function() {
    count = count + 1;
    $('[item-list]').append(`
      <tr id="row_${count}" class="ola">
          <td>
                <select class="form-control item" id="item${count}" name="item[]"  select-item>
                  <option value="0">Select Item</option>
                    @if($items->count() > 0)
                      @foreach($items as $item)
                      <option value="{{$item->id}}">{{$item->name}}</option>
                      @endforeach
                    @endif
                </select>
              </td>
              <td>
              <textarea id="item_description" name="item_description[]" rows="4" 
              class="form-control" placeholder="Item Description" required></textarea>
              </td>
              <td>
                  
                  <input type="text" name="quantity[]" id="quantity${count}"
                  class="form-control quantity" value="1.00">
              </td>
              <td>
                  <input type="text" name="unit_cost[]" id="unit_cost${count}"
                  class="form-control cost" value="1.00"  readonly>
              </td>
              <td class="bg-light" total id="tot"></td>
              <td>
                  <input type="checkbox" name="record">

                </td>
            </tr>
        </tr>
    `)

    // get selected item unit cost
    $("[select-item]").change(function(event){
      var sol = $(this).parents("tr");
      var selected = null;
      var selected = sol.find("[select-item]").val();
      if(selected == 0){
        sol.find(".cost").val('0.00');
        sol.find("[total]").text('0.00');
      }else {
        $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        })
        $.ajax({
          url: "{{ route('getPrice', ['businessCode' => $businessInfo->business_code]) }}",
          method: "POST",
          data: {
            id: selected
          },
          success: function (data) {
            sol.find( ".cost" ).val(data['data']);
            var quantity = sol.find( ".quantity" ).val();
            var unit = sol.find( ".cost" ).val();
            var total = quantity * unit;
            sol.find( "[total]" ).text( total );
            calculateSum();
          },
          error: function(err) {
            console.log(err);
          }
        }) 
        }
    })

  $( ".quantity" )
      .keyup(function(e) {
        var sol = $(this).parents("tr");
        var quantity = sol.find( ".quantity" ).val();
        var unit = sol.find( ".cost" ).val();
        var total = quantity * unit;
        sol.find( "[total]" ).text( total );
        calculateSum();
      })
 
  });
  
function calculateSum() {
  var subtotal = 0;
  $("[item-list] tr").find('td:eq(4)').each(function(){
      subtotal += parseFloat($(this).text());
  }) 
  $("#total_sum_value").html("&#8358; " + subtotal.toLocaleString() );
  $("#real-total").html("&#8358; " + subtotal.toLocaleString() );
   total_sum = subtotal;
}

$("#discount").keyup(function(e) {
      var discount_value = $(this).val();
      calculateDiscountTotal(discount_value)
  })

  function calculateDiscountTotal(discount_value) {
    if(discount_value > 0) {
        var discount = (discount_value * total_sum) / 100;
        $("#discount-total").html("&#8358; " + discount.toLocaleString() );
        total_sum = total_sum - discount;
        $("#real-total").html("&#8358; " + total_sum.toLocaleString() );
      }else {
        $("#discount-total").html("&#8358; 0.0" );
        $("#real-total").html("&#8358; " + total_sum.toLocaleString() );
      }
  }

  $("#vat").keyup(function(e) {
      var vat_value = $(this).val();
      calculateVatTotal(vat_value);
  })

  function calculateVatTotal(vat_value) {
    var vat = (vat_value * total_sum) / 100;
      if(vat_value > 0) {
        var vat = (vat_value * total_sum) / 100;
        $("#vat-total").html("&#8358; " + vat.toLocaleString() );
        if(discount_sum == 0){
            vat_sum = total_sum + vat;
          }else {
            vat_sum = discount_sum + vat;
          }
        $("#real-total").html("&#8358; " + vat_sum.toLocaleString() );
      }
  }
  

  $("[remove-row]").click(function(){
          $("table tbody").find('input[name="record"]').each(function(){
            if($(this).is(":checked")){
                  $(this).parents("tr").remove();
              }
          });
      })


  
        $('#user_form').on('submit', function (event) {
                event.preventDefault();
                var count_data = 0;

                $('.item').each(function () {
                    count_data = count_data + 1;
                });
                // console.log(23);
                if (count_data > 0) {
                    var form_data = $(this).serialize();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })
                    $.ajax({
                        url: "{{ route('invoice.store', ['businessCode' => $businessInfo->business_code]) }}",
                        method: "POST",
                        data: form_data,
                        success: function (data) {
                            var success_message = data[0];
                            //redirect to invoice.show url
                            window.location.replace(data[1]);
                            
                            $("#user_form").trigger("reset");
                            $('#user_data').find("tr:gt(0)").remove();
                            $("#discount-total").html("");
                            $("#total_sum_value").html("");
                            $("#real-total").html("");
                            $("[total]").html("");
                            $(function(){ 
                                toastr.success(success_message, 'Success' , {
                                closeButton: true,
                                progressBar: true,
                                });
                              })
                        },
                        error: function(err) {
                          console.log(err);
                        }
                    })
                }

                else {
                    $('#action_alert').html('<p>Please Add atleast one data</p>');
                    // $('#action_alert').dialog('open');
                }
            });
      
      
      })
      </script>

  </main>
@endsection

resources/views/dashboard/invoice/invoice-sidemenu.blade.php
<nav>
    <a href="{{ route('invoice.create', ['businessCode' => $businessInfo->business_code]) }}" class="btn btn-danger btn-block">New Invoice</a>
    <ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('invoice.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-rocket"></i> Sent </a>
    </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('items.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-eercast"></i> Items </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fa fa-bookmark"></i> Draft </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('customers.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-address-book"></i> Customers </a>
      </li>
    </ul>
  </nav>

resources/views/dashboard/invoice/invoice_template.blade.php
@extends('dashboard.template')

@section('main')
<main class="main">

  <!-- Breadcrumb -->
  <ol class="breadcrumb no-print">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="#">Admin</a></li>
    <li class="breadcrumb-item active">Invoice</li>
    @yield('invoice-breadcrumb')
  </ol>

  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="email-app mb-4">
        {{-- @include('dashboard.invoice-sidemenu') --}}

        @yield('invoice-inbox')
        
      </div>
    </div>

  </div>
  <!-- /.conainer-fluid -->
  
</main>
@endsection