routes/web.php
<?php

use App\Account;
use App\Business;
use App\Invoice;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('homepage');
Route::get('/old', 'PagesController@oldindex')->name('oldhomepage');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/pricing', 'PagesController@pricing')->name('pricing');
Route::resource('contactus', 'ContactusController');

// Errors ROute
Route::get('/404', function() {
	return view('dashboard.404_page');
})->name('404');


Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/new_plan', 'SubscriptionPlanController@store')->name('plan');

Route::get('users_list', 'UsersController@UsersList');
Route::post('/new_accounts', 'AccountsController@store')->name('accounts');

Route::resource('subscription_plan', 'SubscriptionPlanController');
Route::resource('business', 'BusinessController');
Route::resource('subscribe', 'SubscribersController');
Route::resource('accounts', 'AccountsController');

Route::group(['prefix'=>'{businessCode}', 'middleware'=>['businessMiddleware']],function($businessCode){
	Route::resource('dashboard', 'DashboardController');
	// Route::resource('businessaccounts', 'BusinessAccountsController');
	Route::resource('chartofaccounts', 'ChartOfAccountsController');
	Route::resource('journal', 'JournalController')->middleware('CheckSubscription');
	Route::resource('users', 'UsersController')->middleware(['CheckSubscription', 'Subscription']);

	Route::resource('userbusiness', 'UserBusinessController');
	// Route::get('12mcashflow', 'CashFlowController@months12');
	Route::resource('invoice', 'InvoiceController');
	Route::resource('customers', 'CustomerController');
	Route::resource('items', 'ItemController');

	/**
	 * Reporting Routes
	 */
	Route::resource('income_statement', 'IncomeStatementController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('cashflow', 'CashFlowController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('balance_sheet', 'BalanceSheetController')->middleware(['CheckSubscription', 'Subscription']);
	/**
	 * Get reporting details route
	 */
	Route::post('getbalancesheet', 'BalanceSheetController@getBalancesheet')->name('getBS');
	Route::post('getcashflow', 'CashFlowController@getCashFlow')->name('getCF');
	Route::post('items.price', 'ItemController@showPrice')->name('getPrice');

	Route::get('income-generate-pdf/{start_date}/{end_date}','IncomeStatementController@generatePDF')->name('income-generate-pdf');
	Route::get('balance-generate-pdf/{start_date}/{end_date}','BalanceSheetController@generatePDF')->name('balance-generate-pdf');
	Route::get('cashflow-generate-pdf/{start_date}/{end_date}','CashFlowController@generatePDF')->name('cashflow-generate-pdf');
	Route::get('download-pdf/{id}','InvoiceController@downloadInvoiceasPDF')->name('download-pdf');

});




Route::get('/industries/{account_id}', function ($account_id) {
	$account = Account::where('id','=',$account_id)->first();

	return $account->accounttype->name;
	// $json = asset('static/industries.json');
 //    return $json;
});

//Paystack route
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay'); 
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

Route::get('export','IncomeStatementController@export')->name('export');


Route::get('mailable/{businesscode}/{id}', function ($businessCode,$id) {
	$business = Business::where(['business_code'=>$businessCode])->first();
	$invoice = Invoice::where(['id'=>$id,'business_id'=>$business->id])->first();
	if($invoice){
		return new App\Mail\InvoiceMail($invoice);
	}else {
		return view('dashboard.404_page');
	}
})->name('mailable');

// Route::get('/play', function() {

// 	$j =  Invoice::generateInvoiceCode();
// 	return $j;
// });

Route::get('/bela', function() {
	return view('dashboard.pdf.cashflow_dataPDF');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Business;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($businessCode)
    {
        // Route::current()->parameter('id');
        $businesses = DB::table('businesses')
                    ->leftJoin('user_businesses', 'businesses.id', '=', 'user_businesses.business_id')
                    ->where('user_businesses.user_id', '=', auth()->user()->id)
                    ->select('businesses.*')
                    ->orderBy('businesses.id','asc')
                    ->get();
        $businessInfo = DB::table('businesses')
                        ->where('businesses.business_code', '=', $businessCode)
                        ->first();
        $customers = DB::table('customers')
                        ->where('customers.business_id', '=', $businessInfo->id)
                        ->select('customers.*')
                        ->get();
        $items =  DB::table('items')
                        ->where('items.business_id', '=', $businessInfo->id)
                        ->leftJoin('accounts', 'items.account_id', '=', 'accounts.id')
                        ->select('items.*','accounts.account_name')
                        ->get();
        $invoices =  DB::table('invoices')
                        ->where('invoices.business_id', '=', $businessInfo->id)
                        ->select('invoices.*')
                        ->get();
        $transactions =  DB::table('transactions')
                        ->where('transactions.business_id', '=', $businessInfo->id)
                        ->select('transactions.*')
                        ->get();
        $cash_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 1)
                        ->select('client_ledger.*')
                        ->get();
        $all_cash_balances = array_pluck($cash_ledger, 'balance');
        $last_cash = last($all_cash_balances);

        $sales_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 14)
                        ->select('client_ledger.*')
                        ->get();

        $service_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 15)
                        ->select('client_ledger.*')
                        ->get();
        // return count($sales_revenue_ledger);
        if(count($sales_revenue_ledger) > 0)
        {
            $all_revenue_balances = array_pluck($sales_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);
        }
        else {
            $all_revenue_balances = array_pluck($service_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);  
        }
        return view('dashboard.dashboard', compact('businesses', 'businessInfo','customers','items',
        'invoices','transactions','last_cash','last_revenue'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/12mcash_flow.blade.php
@extends('dashboard.template')

@section('main')
<main class="main">

  <!-- Breadcrumb -->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="#">Admin</a></li>
    <li class="breadcrumb-item active">Cash Flow</li>
  </ol>

  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        Cash Flow Statement
        <strong>#90-98792</strong>
        <a href="#" class="btn btn-sm btn-info float-right" onclick="javascript:window.print();"><i class="fa fa-print"></i> Print</a>
      </div>
         <!--/.col-->
         <div class="float-right mt-3 mr-2">
            <button type="button" class="btn btn-primary float-right"><i class="icon-cloud-download"></i> Download</button>
            <div class="btn-group btn-group-toggle float-right mr-3" data-toggle="buttons">
              <label class="btn btn-outline-secondary active">
                <input type="radio" name="options" id="option2" autocomplete="off" checked="">12 Month
              </label>
              <label class="btn btn-outline-secondary">
                <input type="radio" name="options" id="option3" autocomplete="off"> Year
              </label>
            </div>
          </div>
          <!--/.col-->
     
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12 text-center bg-secondary">
            <strong><h4>Company Name</h4></strong>
          </div>
          <div class="col-sm-12 text-center bg-info">
            <h4 class="bold">Cash Flow Statement</h4>
        </div>
        </div>
        <!--/.row-->
          <section>
                <div class="row float-right">
                <div class="col-5-sm">For the year Ending:</div>
                <div class="col"> 12/09/2019 </div>
                </div>
                <br>
                <div class="row float-right">
                <div class="col-5-sm">Cash at Beginning of Year:</div>
                <div class="col"> N78,908 </div>
                </div>
          </section>
             
                 <table class="table table-responsive-sm">
                  <thead>
                    <tr class="bg-success">
                        <th scope="col">Operations</th>
                        <th scope="col">Jan'16</th>
                        <th scope="col">Feb'16</th>
                        <th scope="col">Mar'16</th>
                        <th scope="col">Apr'16</th>
                        <th scope="col">May'16</th>
                        <th scope="col">Jun'16</th>
                        <th scope="col">Jul'16</th>
                        <th scope="col">Aug'16</th>
                        <th scope="col">Sept'16</th>
                        <th scope="col">Oct'16</th>
                        <th scope="col">Nov'16</th>
                        <th scope="col">Dec'16</th>
                      </tr>
                      <tr class="table-success">
                          <th scope="col">Cash recipts from</th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                          <th scope="col"></th>
                        </tr>
                  </thead>
                  <tbody>
                      <!-- @foreach ($entityLedger->where('accttype','=','Assets') as $item) -->
                      <tr>
                          <td>{{$item->name}}sdsd</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                          <td>{{$item->total_balance}}sds</td>
                        </tr>
                      <!-- @endforeach -->
                      <tr>
                        <th class="pl-5">Net Cash Flow From Operations</th>
                        <td class="bg-light">&#8358;{!!$entityLedger->where('accttype','=','Assets')->sum('total_balance' )!!}</td>
                      </tr>
                  </tbody>
                </table>


                    <table class="table table-responsive-sm">
                  <thead>
                    <tr class="bg-success">
                        <th scope="col">Investing Activities</th>
                        <th scope="col">{{date('Y')}}</th>
                      </tr>
                      <tr class="table-success">
                          <th scope="col">Cash recipts from</th>
                          <th scope="col"></th>
                        </tr>
                  </thead>
                  <tbody>
                      <!-- @foreach ($entityLedger->where('accttype','=','Assets') as $item) -->
                      <tr>
                          <td>{{$item->name}}sdsd</td>
                          <td>{{$item->total_balance}}sds</td>
                        </tr>
                      <!-- @endforeach -->
                      <tr>
                        <th class="pl-5">Net Cash Flow from Investing Activities</th>
                        <td class="bg-light">&#8358;{!!$entityLedger->where('accttype','=','Assets')->sum('total_balance' )!!}</td>
                      </tr>
                  </tbody>
                </table>

                    <table class="table table-responsive-sm">
                  <thead>
                    <tr class="bg-success">
                        <th scope="col">Financing Activities</th>
                        <th scope="col">{{date('Y')}}</th>
                      </tr>
                      <tr class="table-success">
                          <th scope="col">Cash recipts from</th>
                          <th scope="col"></th>
                        </tr>
                  </thead>
                  <tbody>
                      <!-- @foreach ($entityLedger->where('accttype','=','Assets') as $item) -->
                      <tr>
                          <td>{{$item->name}}sdsd</td>
                          <td>{{$item->total_balance}}sds</td>
                        </tr>
                      <!-- @endforeach -->
                      <tr>
                        <th class="pl-5">Net Cash Flow from Financing Activites</th>
                        <td class="bg-light">&#8358;{!!$entityLedger->where('accttype','=','Assets')->sum('total_balance' )!!}</td>
                      </tr>

                       <tr class="bg-light">
                        <th>Net Increase in Cash</th>
                        <td >&#8358;{!!$entityLedger->where('accttype','=','Assets')->sum('total_balance' )!!}</td>
                      </tr>

                       <tr>
                        <th class="pl-5">Cash at End of Year</th>
                        <td class="bg-light">&#8358;{!!$entityLedger->where('accttype','=','Assets')->sum('total_balance' )!!}</td>
                      </tr>
                  </tbody>
                </table>
            
    

        </div>
        <!-- cardbody -->

      </div>
    </div>
  <!-- /.conainer-fluid -->
</main>
@endsection

resources/views/dashboard/404_page.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Account Management System">
  <meta name="author" content="StartUpClerk">
  <meta name="keyword" content="">
  <link rel="shortcut icon" href="{{ asset('img/logoi.png') }}">

  <title>StartUpClerk | 404</title>

  <link href="{{ asset('vendors/css/font-awesome.min.css') }}" rel="stylesheet">
  <link href="{{ asset('vendors/css/simple-line-icons.min.css') }}" rel="stylesheet">

  <!-- Main styles for this application -->
  <link href="{{ asset('css/style.css') }}" rel="stylesheet">


</head>

<body class="app flex-row align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="clearfix">
          <h1 class="float-left display-3 mr-4">404</h1>
          <h4 class="pt-3"><a href="{{ route('home') }}">StartUpClerk</a></h4>
          <p class="text-muted">
            Oops! You're lost. <br>
            The page you are looking for was not found.</p>
        </div>
          
      </div>
    </div>
  </div>



</body>
</html>

resources/views/dashboard/account-view.blade.php
@extends('dashboard.template')


@section('page-title')
  {{$account->account_name}}
@endsection

@section('view-style')
  <link href="{{ asset('vendors/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
  <style>
    .no-display{
      display: none;
    }
    @media only screen and (max-width: 600px) {
      .no-display {
        display: inline;
      }
    }
  </style>
@endsection

@section('main')
<main class="main">

  <!-- Breadcrumb -->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item"><a href="{{ route('chartofaccounts.index', ['businessCode' => $businessInfo->business_code]) }}">Chart of Accounts</a></li>
    <li class="breadcrumb-item active">{{$account->account_name}}</li>

  </ol>

  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        {{$account->account_name}}
        <strong>#{{$transactions->count()}}</strong>
        <a href="#" class="btn btn-sm btn-info float-right" onclick="javascript:window.print();"><i class="fa fa-print"></i> Print</a>
      </div>
      <div class="card-body">
        <div class="mb-3">
          <div><b>{{$account->account_name}}</b></div>
          <div> <b>Code:</b> {{$account->code}} </div>
          <div> <b>Type:</b> {{$account->accounttype->name}} </div>
        </div>
        <table class="table table-striped table-bordered dt-responsive nowrap datatable " style="width:100%;border-collapse: collapse !important">
          <thead>
            <tr>
              <th>#</th>
              <th>Action</th>
              <th>Amount</th>
              <th>Description</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
              @if($transactions->count() > 0)
                @foreach($transactions as $transaction)
                  <tr>
                    <td> <b> <i class="icon-list no-display"></i> {{$loop->iteration}} </b> </td>
                    <td> @if($transaction->entity_type == 'C'){{ 'Credit' }} @else {{ 'Debit' }} @endif</td>
                    <td>{{$transaction->amount}}</td>
                    <td>{{$transaction->description}}</td>
                    <td>{{date('d-F-Y', strtotime($transaction->created_at))}}</td>
                  </tr>
              @endforeach
            @endif
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- /.conainer-fluid -->
</main>

@endsection

@section('view-scripts')
  <script src="{{ asset('vendors/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendors/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('js/views/datatables.js') }}"></script>
  <script src="{{ asset('js/views/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('js/views/responsive.bootstrap4.min.js') }}"></script>
@endsection

resources/views/dashboard/aside.blade.php
<aside class="aside-menu">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab"><i class="icon-list"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#messages" role="tab"><i class="icon-speech"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#settings" role="tab"><i class="icon-settings"></i></a>
      </li>
    </ul>
    <!-- Tab panes -->

  </aside>

resources/views/dashboard/footer.blade.php
<footer class="app-footer">
    <span> 
        {{ config('app.name', 'StartupClerk') }} &copy; 
          <script>
          document.write(new Date().getFullYear())
          </script>
        </span>
  </footer>

resources/views/dashboard/header.blade.php
<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{url('business')}}"></a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="nav navbar-nav d-md-down-none mr-auto">
      <li class="nav-item px-3">
        <a class="nav-link" href="{{url('business')}}">My Businesses
        </a>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      @if(Request::route()->getName() != 'business.index')
      <li class="nav-item dropdown">
        <a class="nav-link nav-link"  href="{{route('users.show', ['businessCode' => $businessInfo->business_code,'user' => Auth::user()->id])}}">
          <img src="{{asset('img/avatars/'.Auth::user()->profile_photo) }}" class="img-avatar" alt="{{Auth::user()->name}}">
        </a>
      </li>
      @endif

      <li class="nav-item dropdown ">
        <a class="nav-link mr-3" data-toggle="dropdown" href="#" role="button" 
        aria-haspopup="true" aria-expanded="false" href="{{ route('logout') }}"
          onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
           <i class="icon-power"></i> 
           <span class="d-md-down-none">Logout</span> 
       </a>

       <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
           @csrf
       </form>
   </li>
    </ul>
  </header>

resources/views/dashboard/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
      @if(Request::route()->getName() != 'business.index')
      <ul class="nav">
        <li class="nav-item">

          <a class="nav-link" href="@if($businesses->count() > 0) {{ route('dashboard.index', ['businessCode' => $businessInfo->business_code]) }} @else # @endif">
            <i class="icon-speedometer"></i> Dashboard
           </a>
        </li>
        <li class="divider m-2"></li>
        @if($businesses->count() > 0)
        <li class="nav-title">
          management
        </li>
        <li class="nav-item nav-dropdown">
          <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-compass"></i> Invoice</a>
          <ul class="nav-dropdown-items">
            <li class="nav-item">
              <a class="nav-link" href="{{ route('invoice.create', ['businessCode' => $businessInfo->business_code]) }}"><i class="icon-note"></i> Create</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('invoice.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-rocket"></i> Sent</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('items.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-eercast"></i> Items</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('customers.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-address-book"></i> Customers</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link @if(Request::route()->getName() == 'users.index') active @endif" 
            href="{{ route('users.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-users"></i> Users
              </a>
          </li>
          <li class="nav-item">
            <a class="nav-link @if(Request::route()->getName() == 'journal.index') active @endif" 
            href="{{ route('journal.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="icon-map"></i> Accounting Journal
              </a>
          </li>
          <li class="nav-item">
            <a class="nav-link @if(Request::route()->getName() == 'chartofaccounts.index') active @endif" 
            href="{{ route('chartofaccounts.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-line-chart"></i> Chart Of Accounts
              </a>
          </li>

        <li class="nav-title">
            Report
          </li>
          <li class="nav-item">
            <a class="nav-link @if(Request::route()->getName() == 'cashflow.index') active @endif" 
            href="{{ route('cashflow.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="icon-pie-chart"></i> Cash Flow</a>
          </li>
        <li class="nav-item">
          <a class="nav-link @if(Request::route()->getName() == 'balance_sheet.index') active @endif" 
          href="{{ route('balance_sheet.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-pie-chart"></i> Balance Sheet
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link @if(Request::route()->getName() == 'income_statement.index') active @endif" 
            href="{{ route('income_statement.index', ['businessCode' => $businessInfo->business_code]) }}"><i class="fa fa-cubes"></i> Income Statement
            </a>
        </li>

        <li class="divider m-2"></li>


        @endif
      </ul>

    </nav>
    @endif
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
  </div>

resources/views/dashboard/user_profile.blade.php
@extends('dashboard.template')

@section('page-title')
    {{Auth::user()->name}}
@endsection

@section('main')
<main class="main">

  <!-- Breadcrumb -->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item active">Profile</li>
  </ol>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <h3>{{Auth::user()->name}} </h3>
            <img src="{{asset('img/avatars/'.Auth::user()->profile_photo) }}" 
                class="img-avatar mb-3" alt="{{Auth::user()->name}}" style="width:140px;height:200px" >
                <div class="form-group">
        <form method="POST" action="{{ route('users.update', ['businessCode' => $businessInfo->business_code,'user' => Auth::user()->id]) }}" enctype="multipart/form-data">
              @csrf
              <input type="hidden" name="_method" value="PUT">
            <label for="profile_photo">Profile Photo:</label> <br>
            <input type="file" name="profile_photo" id="profile_photo">
            @error('profile_photo')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror 
            <div class="form-group mb-0 mt-4">
                <button type="submit" class="btn btn-primary btn-sm" onclick="disabled">
                    Change Photo
                </button>
            </div>
          </form>
        
                </div>
            <div class="row">
              <div class="col-sm-3">Fullname</div>
              <div class="col-sm-7">{{Auth::user()->name}}</div>
            </div>
            <div class="row">
              <div class="col-sm-3">Email</div>
              <div class="col-sm-7">{{Auth::user()->email}}</div>
            </div>
            <div class="row">
              <div class="col-sm-3">Joined Date</div>
              <div class="col-sm-7">{{Auth::user()->created_at}}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.conainer-fluid -->
</main>
@endsection