routes/web.php
<?php

use App\Account;
use App\Business;
use App\Invoice;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('homepage');
Route::get('/old', 'PagesController@oldindex')->name('oldhomepage');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/pricing', 'PagesController@pricing')->name('pricing');
Route::resource('contactus', 'ContactusController');

// Errors ROute
Route::get('/404', function() {
	return view('dashboard.404_page');
})->name('404');


Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/new_plan', 'SubscriptionPlanController@store')->name('plan');

Route::get('users_list', 'UsersController@UsersList');
Route::post('/new_accounts', 'AccountsController@store')->name('accounts');

Route::resource('subscription_plan', 'SubscriptionPlanController');
Route::resource('business', 'BusinessController');
Route::resource('subscribe', 'SubscribersController');
Route::resource('accounts', 'AccountsController');

Route::group(['prefix'=>'{businessCode}', 'middleware'=>['businessMiddleware']],function($businessCode){
	Route::resource('dashboard', 'DashboardController');
	// Route::resource('businessaccounts', 'BusinessAccountsController');
	Route::resource('chartofaccounts', 'ChartOfAccountsController');
	Route::resource('journal', 'JournalController')->middleware('CheckSubscription');
	Route::resource('users', 'UsersController')->middleware(['CheckSubscription', 'Subscription']);

	Route::resource('userbusiness', 'UserBusinessController');
	// Route::get('12mcashflow', 'CashFlowController@months12');
	Route::resource('invoice', 'InvoiceController');
	Route::resource('customers', 'CustomerController');
	Route::resource('items', 'ItemController');

	/**
	 * Reporting Routes
	 */
	Route::resource('income_statement', 'IncomeStatementController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('cashflow', 'CashFlowController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('balance_sheet', 'BalanceSheetController')->middleware(['CheckSubscription', 'Subscription']);
	/**
	 * Get reporting details route
	 */
	Route::post('getbalancesheet', 'BalanceSheetController@getBalancesheet')->name('getBS');
	Route::post('getcashflow', 'CashFlowController@getCashFlow')->name('getCF');
	Route::post('items.price', 'ItemController@showPrice')->name('getPrice');

	Route::get('income-generate-pdf/{start_date}/{end_date}','IncomeStatementController@generatePDF')->name('income-generate-pdf');
	Route::get('balance-generate-pdf/{start_date}/{end_date}','BalanceSheetController@generatePDF')->name('balance-generate-pdf');
	Route::get('cashflow-generate-pdf/{start_date}/{end_date}','CashFlowController@generatePDF')->name('cashflow-generate-pdf');
	Route::get('download-pdf/{id}','InvoiceController@downloadInvoiceasPDF')->name('download-pdf');

});




Route::get('/industries/{account_id}', function ($account_id) {
	$account = Account::where('id','=',$account_id)->first();

	return $account->accounttype->name;
	// $json = asset('static/industries.json');
 //    return $json;
});

//Paystack route
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay'); 
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

Route::get('export','IncomeStatementController@export')->name('export');


Route::get('mailable/{businesscode}/{id}', function ($businessCode,$id) {
	$business = Business::where(['business_code'=>$businessCode])->first();
	$invoice = Invoice::where(['id'=>$id,'business_id'=>$business->id])->first();
	if($invoice){
		return new App\Mail\InvoiceMail($invoice);
	}else {
		return view('dashboard.404_page');
	}
})->name('mailable');

// Route::get('/play', function() {

// 	$j =  Invoice::generateInvoiceCode();
// 	return $j;
// });

Route::get('/bela', function() {
	return view('dashboard.pdf.cashflow_dataPDF');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Business;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($businessCode)
    {
        // Route::current()->parameter('id');
        $businesses = DB::table('businesses')
                    ->leftJoin('user_businesses', 'businesses.id', '=', 'user_businesses.business_id')
                    ->where('user_businesses.user_id', '=', auth()->user()->id)
                    ->select('businesses.*')
                    ->orderBy('businesses.id','asc')
                    ->get();
        $businessInfo = DB::table('businesses')
                        ->where('businesses.business_code', '=', $businessCode)
                        ->first();
        $customers = DB::table('customers')
                        ->where('customers.business_id', '=', $businessInfo->id)
                        ->select('customers.*')
                        ->get();
        $items =  DB::table('items')
                        ->where('items.business_id', '=', $businessInfo->id)
                        ->leftJoin('accounts', 'items.account_id', '=', 'accounts.id')
                        ->select('items.*','accounts.account_name')
                        ->get();
        $invoices =  DB::table('invoices')
                        ->where('invoices.business_id', '=', $businessInfo->id)
                        ->select('invoices.*')
                        ->get();
        $transactions =  DB::table('transactions')
                        ->where('transactions.business_id', '=', $businessInfo->id)
                        ->select('transactions.*')
                        ->get();
        $cash_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 1)
                        ->select('client_ledger.*')
                        ->get();
        $all_cash_balances = array_pluck($cash_ledger, 'balance');
        $last_cash = last($all_cash_balances);

        $sales_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 14)
                        ->select('client_ledger.*')
                        ->get();

        $service_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 15)
                        ->select('client_ledger.*')
                        ->get();
        // return count($sales_revenue_ledger);
        if(count($sales_revenue_ledger) > 0)
        {
            $all_revenue_balances = array_pluck($sales_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);
        }
        else {
            $all_revenue_balances = array_pluck($service_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);  
        }
        return view('dashboard.dashboard', compact('businesses', 'businessInfo','customers','items',
        'invoices','transactions','last_cash','last_revenue'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/forms/add_account.blade.php
<form method="POST" action="{{ route('chartofaccounts.store', ['businessCode' => $businessInfo->business_code]) }}">
    @csrf
    <div class="form-group row">
        <label class="col-md-3 col-form-label" for="account_name">Account Name*</label>
        <div class="col-md-9">
          <input type="text" id="account_name" name="account_name" class="form-control" placeholder="account name" value="{{ old('account_name') }}">
          <span class="help-block">e.g Sales of Bugdget</span>
        </div>
        @error('account_name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label" for="type_id">Account Type*</label>
        <div class="col-md-9">
          <select class="form-control" id="type_id" name="type_id">
            @foreach($accountTypes as $accountType)
            <option value="{{$accountType->id}}">{{$accountType->name}}</option>
            @endforeach
        </select>
        </div>
      </div>
    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="entity_type">Entity Type*</label>
      <div class="col-md-9">
        <select class="form-control" id="entity_type" name="entity_type">
          <option value="Debit">Debit</option>
          <option value="Credit">Credit</option>
      </select>
      </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label" for="code">Account Code*</label>
        <div class="col-md-9">
          <input type="text" id="code" name="code" class="form-control" placeholder="account code" value="{{ old('code') }}">
          <span class="help-block">e.g 311123</span>
        </div>
        @error('code')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
      </div>
    <div class="form-group mb-0">
        <button type="submit" class="btn btn-primary" onclick="disabled">
            Submit
        </button>
    </div>
</form>

resources/views/dashboard/forms/add_business.blade.php
<form method="POST" action="{{ route('business.store') }}" enctype="multipart/form-data" id="addBusinessForm">
        @csrf
    <div class="form-group">
        <label for="name">Business Name:</label>
        <input input id="name" type="text" class="form-control 
            @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" 
            placeholder="Enter Company Name" required autofocus>
    </div>
    <div class="form-group">
      <label for="companylogo">Business Logo:</label> <br>
      <input type="file" name="company_logo" id="companylogo"> 
    </div>
    <div class="form-group">
        <label for="address">Business Address:</label>
        <input input id="address" type="text" class="form-control 
            @error('address') is-invalid @enderror" name="address" value="{{ old('address') }}" 
            placeholder="Enter Company address" required autofocus>
    </div>
    <div class="form-group">
        <label for="phone">Business Phone:</label>
        <input input id="phone" type="text" class="form-control 
            @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" 
            placeholder="Enter Company phone" required autofocus>
    </div>
    <div class="form-group">
        <label for="email">Business email:</label>
        <input input id="email" type="text" class="form-control 
            @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" 
            placeholder="Enter Company email" required autofocus>
    </div>
    <div class="form-group">
        <label for="website">Business website:</label>
        <input input id="website" type="text" class="form-control" name="website" value="{{ old('website') }}" 
            placeholder="Enter Company website" autofocus>
    </div>
    <div class="row">
            <div class="form-group col-sm-8">
              <label for="country">Country</label>
              <select class="form-control" id="country" name="country">
            </select>
            </div>
            <div class="form-group col-sm-4">
              <label for="state">State</label>
            <select class="form-control" id="state" name="state">
            </select>
            </div>
          </div>
    <div class="form-group">
        <label for="category">Category:</label>
        <select class="form-control" id="category" name="category">
            </select>
    </div>
    <div class="form-group">
        <label for="founders">Business founders:(e.g Mark, Jude)</label>
        <textarea id="founders" class="form-control 
            @error('founders') is-invalid @enderror" name="founders" cols="10" rows="3" required autofocus>
            {{ old('founders') }}
            </textarea>
    </div>
    <div class="form-group">
        <label for="members">Business Size: (e.g 2)</label>
        <input id="members" type="text" class="form-control 
        @error('members') is-invalid @enderror" name="members" value="{{ old('members') }}" required autofocus>            
    </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" class="form-control
            @error('description') is-invalid @enderror" name="description"  cols="10" rows="3" required autofocus>
            {{ old('description') }}
            </textarea>  
        </div>   
        <div class="form-group mb-0">
                <button type="submit" class="btn btn-primary" onclick="disabled">
                    {{ __('Submit') }}
                </button>
        </div>
    </form>

resources/views/dashboard/forms/add_customer.blade.php
<form method="POST" action="{{ route('customers.store', ['businessCode' => $businessInfo->business_code]) }}">
    @csrf
<div class="form-group">
  <label for="business_name">Business Name</label>
  <input type="text" class="form-control" name="business_name" id="business_name" placeholder="Enter Business Name">
</div>
<div class="row">
    <div class="form-group col-sm-6">
      <label for="fname">First Name</label>
      <input type="text" class="form-control" name="fname" id="fname" placeholder="First Name">
    </div>
    <div class="form-group col-sm-6">
      <label for="lname">Last Name</label>
      <input type="text" class="form-control" name="lname" id="lname" placeholder="Last Name">
    </div>
  </div>
<div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email">
  </div>
<div class="form-group">
  <label for="customer_address">Address</label>
  <textarea id="textarea-input" name="customer_address" rows="3" 
  class="form-control" placeholder="Content.."></textarea>
</div>

<div class="row">
  <div class="form-group col-sm-6">
    <label for="customer_city">City</label>
    <input type="text" class="form-control" name="customer_city" id="customer_city"  placeholder="Enter your city">
  </div>
  <div class="form-group col-sm-6">
    <label for="customer_tel">Tel</label>
    <input type="text" class="form-control" name="customer_tel" id="customer_tel" placeholder="Enter Tel Number">
  </div>
</div>
<div class="form-group">
    <label for="customer_state">State</label>
    <input type="text" class="form-control" name="customer_state" id="customer_state" placeholder="Enter State">
</div>
<div class="form-group mb-0">
    <button type="submit" class="btn btn-primary" onclick="disabled">
        Save Customer
    </button>
</div>
</form>

resources/views/dashboard/forms/add_item.blade.php
<form method="POST" action="{{ route('items.store', ['businessCode' => $businessInfo->business_code]) }}">
    @csrf
<div class="form-group row">
    <label class="col-md-3 col-form-label">Type</label>
    <div class="col-md-9 col-form-label">
      <div class="form-check form-check-inline mr-1">
        <input class="form-check-input" type="radio" id="goods" value="Goods" name="type">
        <label class="form-check-label" for="goods">Goods</label>
      </div>
      <div class="form-check form-check-inline mr-1">
        <input class="form-check-input" type="radio" id="service" value="Service" name="type">
        <label class="form-check-label" for="service">Service</label>
      </div>
    </div>
  </div>

<div class="form-group row">
    <label class="col-md-3 col-form-label" for="name">Name</label>
    <div class="col-md-9">
      <input type="text" id="name" name="name" class="form-control" placeholder="Name">
      <span class="help-block">Name of product / service</span>
    </div>
  </div>

<div class="form-group row">
    <label class="col-md-3 col-form-label" for="unit">Unit</label>
    <div class="col-md-9">
      <input type="text" id="unit" name="unit" class="form-control" placeholder="Unit">
      <span class="help-block">e.g Box, cm, g, in, kg, m, lb</span>
    </div>
  </div>
<b>Sales Information </b><br>
<div class="form-group row">
    <label class="col-md-3 col-form-label" for="price">Selling Price</label>
    <div class="col-md-9">
        <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">&#8358;</span>
            </div>
            <input type="text" id="price" name="price" class="form-control" placeholder="Price">
          </div>
    </div>
  </div>

<div class="form-group row">
    <label class="col-md-3 col-form-label" for="account">Account *</label>
    <div class="col-md-9">
      <select class="form-control" id="account" name="account">
        @foreach($accounts as $account)
          @if($account->account_name == 'Sales revenue' || 
              $account->account_name == 'Service revenue' || 
              $account->account_name == 'Accounts receivable')
          <option value="{{$account->id}}">{{$account->account_name}}</option>
          @endif
        @endforeach
    </select>
    </div>
  </div>
<div class="form-group row">
    <label class="col-md-3 col-form-label" for="description">Description</label>
    <div class="col-md-9">
      <textarea id="description" name="description" rows="5" class="form-control" placeholder="Description.."></textarea>
    </div>
  </div>
  <div class="form-group mb-0">
      <button type="submit" class="btn btn-primary" onclick="disabled">
          Submit
      </button>
  </div>
</form>

resources/views/dashboard/forms/add_journal.blade.php
<form method="POST" action="journal" id="addJournalForm">
        @csrf
        <div class="form-group">
            <label for="account">Debit Account:</label>
            <select class="form-control" id="account" name="account_debit">
                <option value="118">Cash</option>
                @foreach($daccounts as $account)
                <option value="{{$account->id}}">{{$account->account_name}}</option>
                @endforeach
            </select>
        </div>
         <div class="form-group">
            <label for="amount">Amount</label>
                <input id="amount" type="text" class="form-control
                 @error('amount') is-invalid @enderror" name="amount" value="{{ old('amount') }}" required autofocus>
                @error('amount')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
        </div>
        <div class="form-group">
            <label for="account">Credit Account:</label>
            <select class="form-control" id="account" name="account_credit">
                @foreach($caccounts as $account)
                <option value="{{$account->id}}">{{$account->account_name}}</option>
                @endforeach
                <option value="118">Cash</option>
            </select>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
                <input id="description" type="text" class="form-control
                 @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autofocus>
                @error('description')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
        </div>



        <div class="form-group mb-0">
                <button type="submit" class="btn btn-primary" onclick="disabled">
                    {{ __('Submit') }}
                </button>
        </div>
    </form>

resources/views/dashboard/forms/add_tax.blade.php
Add Tax
Tax Name
Rate (%)
<div class="col-md-12">
  <div class="input-group">
    <input type="email" id="input2-group1" name="input2-group1" class="form-control" placeholder="Email">
    <div class="input-group-append">
      <span class="input-group-text"><i class="fa fa-percent"></i></span>
    </div>
  </div>
</div>

resources/views/dashboard/forms/add_user.blade.php
<form method="POST" action="users">
    @csrf
<fieldset class="form-group">
    <label>Name</label>
    <div class="input-group">
      <span class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-user-circle"></i></span>
      </span>
      <input type="text" class="form-control"  name="name">
    </div>
  </fieldset>  
<fieldset class="form-group">
    <label>Email</label>
    <div class="input-group">
      <span class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
      </span>
      <input type="text" class="form-control"  name="email">
    </div>
  </fieldset>  
<fieldset class="form-group">
    <label>Password</label>
    <div class="input-group">
      <span class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-asterisk"></i></span>
      </span>
      <input type="password" class="form-control" name="password">
    </div>
  </fieldset>  
<fieldset class="form-group">
    <label>Confirm Password</label>
    <div class="input-group">
      <span class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-asterisk"></i></span>
      </span>
      <input type="password" class="form-control" name="password_confirmation">
    </div>
  </fieldset>  
<fieldset class="form-group">
    <label>Role</label>
    <div class="input-group">
      <span class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-sitemap"></i></span>
      </span>
      <select id="select1"  class="form-control" name="role">
          <option value="0">Please select</option>
          <option value="1">Admin</option>
          <option value="2">Staff</option>
        </select>
    </div>
  </fieldset>  
  <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</button>
  <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
</form>

resources/views/dashboard/forms/edit_business.blade.php
<form method="POST" action="{{ route('business.update', ['business' => $business->id]) }}" enctype="multipart/form-data" id="addBusinessForm">
    @csrf
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" id="e_id" name="id">
    <div class="form-group">
        <label for="name">Business Name:</label>
        <input id="bname" type="text" class="form-control 
            @error('name') is-invalid @enderror" name="name" 
            placeholder="Enter Company Name" required autofocus>
    </div>
    <div class="form-group">
      <label for="companylogo">Business Logo:</label> <br>
      <input type="file" name="company_logo" id="companylogo"> 
    </div>
    <div class="form-group">
        <label for="address">Business Address:</label>
        <input id="baddress" type="text" class="form-control 
            @error('address') is-invalid @enderror" name="address" 
            placeholder="Enter Company address" required autofocus>
    </div>
    <div class="form-group">
        <label for="phone">Business Phone:</label>
        <input id="bphone" type="text" class="form-control 
            @error('phone') is-invalid @enderror" name="phone" 
            placeholder="Enter Company phone" required autofocus>
    </div>
    <div class="form-group">
        <label for="email">Business email:</label>
        <input id="bemail" type="text" class="form-control 
            @error('email') is-invalid @enderror" name="email" 
            placeholder="Enter Company email" required autofocus>
    </div>
    <div class="form-group">
        <label for="website">Business website:</label>
        <input id="bwebsite" type="text" class="form-control" name="website" 
            placeholder="Enter Company website" autofocus>
    </div>
 
    <div class="form-group mb-0">
        <button type="submit" class="btn btn-primary" onclick="disabled">
            {{ __('Update') }}
        </button>
    </div>
    </form>

resources/views/dashboard/forms/edit_customer.blade.php
<form method="POST" action="{{ route('customers.update', ['businessCode' => $businessInfo->business_code, 'customer' => $customer->id]) }}">
    @csrf
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" id="e_id" name="id">
<div class="form-group">
  <label for="business_name">Business Name</label>
  <input type="text" class="form-control" name="business_name" id="e_bname" placeholder="Enter Business Name">
</div>
<div class="row">
    <div class="form-group col-sm-6">
      <label for="fname">First Name</label>
      <input type="text" class="form-control" name="fname" id="e_fname" placeholder="First Name">
    </div>
    <div class="form-group col-sm-6">
      <label for="lname">Last Name</label>
      <input type="text" class="form-control" name="lname" id="e_lname" placeholder="Last Name">
    </div>
  </div>
<div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" name="email" id="e_email" placeholder="Enter Email">
  </div>
<div class="form-group">
  <label for="customer_address">Address</label>
  <textarea id="e_address" name="customer_address" rows="3" 
  class="form-control" placeholder="Content.."></textarea>
</div>

<div class="row">
  <div class="form-group col-sm-6">
    <label for="customer_city">City</label>
    <input type="text" class="form-control" name="customer_city" id="e_city"  placeholder="Enter your city">
  </div>
  <div class="form-group col-sm-6">
    <label for="customer_tel">Tel</label>
    <input type="text" class="form-control" name="customer_tel" id="e_tel" placeholder="Enter Tel Number">
  </div>
</div>
<div class="form-group">
    <label for="customer_state">State</label>
    <input type="text" class="form-control" name="customer_state" id="e_state" placeholder="Enter State">
</div>
<div class="form-group mb-0">
    <button type="submit" class="btn btn-primary" onclick="disabled">
        Save Customer
    </button>
</div>
</form>

resources/views/dashboard/forms/edit_item.blade.php
<form method="POST" action="{{ route('items.update', ['businessCode' => $businessInfo->business_code, 'item' => $item->id]) }}">
    @csrf
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" id="e_id" name="id">
<div class="form-group row">
    <label class="col-md-3 col-form-label">Type</label>
    <div class="col-md-9 col-form-label">
      <div class="form-check form-check-inline mr-1">
        <input class="form-check-input" type="radio" id="e_goods" value="Goods" name="type">
        <label class="form-check-label" for="goods">Goods</label>
      </div>
      <div class="form-check form-check-inline mr-1">
        <input class="form-check-input" type="radio" id="e_service" value="Service" name="type">
        <label class="form-check-label" for="service">Service</label>
      </div>
    </div>
  </div>

<div class="form-group row">
    <label class="col-md-3 col-form-label" for="name">Name</label>
    <div class="col-md-9">
      <input type="text" id="e_name" name="name" class="form-control" placeholder="Name">
      <span class="help-block">Name of product / service</span>
    </div>
  </div>

<div class="form-group row">
    <label class="col-md-3 col-form-label" for="unit">Unit</label>
    <div class="col-md-9">
      <input type="text" id="e_unit" name="unit" class="form-control" placeholder="Unit">
      <span class="help-block">e.g Box, cm, g, in, kg, m, lb</span>
    </div>
  </div>
<b>Sales Information </b><br>
<div class="form-group row">
    <label class="col-md-3 col-form-label" for="price">Selling Price</label>
    <div class="col-md-9">
        <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">&#8358;</span>
            </div>
            <input type="text" id="e_price" name="price" class="form-control" placeholder="Price">
          </div>
    </div>
  </div>

<div class="form-group row">
    <label class="col-md-3 col-form-label" for="account">Account *</label>
    <div class="col-md-9">
      <select class="form-control" id="account" name="account">
        @foreach($accounts as $account)
          @if($account->account_name === 'Sales Revenue' || 
              $account->account_name === 'Service Revenue' || 
              $account->account_name === 'Account Receivable')
          <option value="{{$account->id}}">{{$account->account_name}}</option>
          @endif
        @endforeach
    </select>
    </div>
  </div>
<div class="form-group row">
    <label class="col-md-3 col-form-label" for="description">Description</label>
    <div class="col-md-9">
      <textarea id="e_description" name="description" rows="5" class="form-control" placeholder="Description.."></textarea>
    </div>
  </div>
  <div class="form-group mb-0">
      <button type="submit" class="btn btn-primary" onclick="disabled">
          Submit
      </button>
  </div>
</form>