routes/web.php
<?php

use App\Account;
use App\Business;
use App\Invoice;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PagesController@index')->name('homepage');
Route::get('/old', 'PagesController@oldindex')->name('oldhomepage');
Route::get('/services', 'PagesController@services')->name('services');
Route::get('/pricing', 'PagesController@pricing')->name('pricing');
Route::resource('contactus', 'ContactusController');

// Errors ROute
Route::get('/404', function() {
	return view('dashboard.404_page');
})->name('404');


Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/new_plan', 'SubscriptionPlanController@store')->name('plan');

Route::get('users_list', 'UsersController@UsersList');
Route::post('/new_accounts', 'AccountsController@store')->name('accounts');

Route::resource('subscription_plan', 'SubscriptionPlanController');
Route::resource('business', 'BusinessController');
Route::resource('subscribe', 'SubscribersController');
Route::resource('accounts', 'AccountsController');

Route::group(['prefix'=>'{businessCode}', 'middleware'=>['businessMiddleware']],function($businessCode){
	Route::resource('dashboard', 'DashboardController');
	// Route::resource('businessaccounts', 'BusinessAccountsController');
	Route::resource('chartofaccounts', 'ChartOfAccountsController');
	Route::resource('journal', 'JournalController')->middleware('CheckSubscription');
	Route::resource('users', 'UsersController')->middleware(['CheckSubscription', 'Subscription']);

	Route::resource('userbusiness', 'UserBusinessController');
	// Route::get('12mcashflow', 'CashFlowController@months12');
	Route::resource('invoice', 'InvoiceController');
	Route::resource('customers', 'CustomerController');
	Route::resource('items', 'ItemController');

	/**
	 * Reporting Routes
	 */
	Route::resource('income_statement', 'IncomeStatementController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('cashflow', 'CashFlowController')->middleware(['CheckSubscription', 'Subscription']);
	Route::resource('balance_sheet', 'BalanceSheetController')->middleware(['CheckSubscription', 'Subscription']);
	/**
	 * Get reporting details route
	 */
	Route::post('getbalancesheet', 'BalanceSheetController@getBalancesheet')->name('getBS');
	Route::post('getcashflow', 'CashFlowController@getCashFlow')->name('getCF');
	Route::post('items.price', 'ItemController@showPrice')->name('getPrice');

	Route::get('income-generate-pdf/{start_date}/{end_date}','IncomeStatementController@generatePDF')->name('income-generate-pdf');
	Route::get('balance-generate-pdf/{start_date}/{end_date}','BalanceSheetController@generatePDF')->name('balance-generate-pdf');
	Route::get('cashflow-generate-pdf/{start_date}/{end_date}','CashFlowController@generatePDF')->name('cashflow-generate-pdf');
	Route::get('download-pdf/{id}','InvoiceController@downloadInvoiceasPDF')->name('download-pdf');

});




Route::get('/industries/{account_id}', function ($account_id) {
	$account = Account::where('id','=',$account_id)->first();

	return $account->accounttype->name;
	// $json = asset('static/industries.json');
 //    return $json;
});

//Paystack route
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay'); 
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');

Route::get('export','IncomeStatementController@export')->name('export');


Route::get('mailable/{businesscode}/{id}', function ($businessCode,$id) {
	$business = Business::where(['business_code'=>$businessCode])->first();
	$invoice = Invoice::where(['id'=>$id,'business_id'=>$business->id])->first();
	if($invoice){
		return new App\Mail\InvoiceMail($invoice);
	}else {
		return view('dashboard.404_page');
	}
})->name('mailable');

// Route::get('/play', function() {

// 	$j =  Invoice::generateInvoiceCode();
// 	return $j;
// });

Route::get('/bela', function() {
	return view('dashboard.pdf.cashflow_dataPDF');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Business;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($businessCode)
    {
        // Route::current()->parameter('id');
        $businesses = DB::table('businesses')
                    ->leftJoin('user_businesses', 'businesses.id', '=', 'user_businesses.business_id')
                    ->where('user_businesses.user_id', '=', auth()->user()->id)
                    ->select('businesses.*')
                    ->orderBy('businesses.id','asc')
                    ->get();
        $businessInfo = DB::table('businesses')
                        ->where('businesses.business_code', '=', $businessCode)
                        ->first();
        $customers = DB::table('customers')
                        ->where('customers.business_id', '=', $businessInfo->id)
                        ->select('customers.*')
                        ->get();
        $items =  DB::table('items')
                        ->where('items.business_id', '=', $businessInfo->id)
                        ->leftJoin('accounts', 'items.account_id', '=', 'accounts.id')
                        ->select('items.*','accounts.account_name')
                        ->get();
        $invoices =  DB::table('invoices')
                        ->where('invoices.business_id', '=', $businessInfo->id)
                        ->select('invoices.*')
                        ->get();
        $transactions =  DB::table('transactions')
                        ->where('transactions.business_id', '=', $businessInfo->id)
                        ->select('transactions.*')
                        ->get();
        $cash_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 1)
                        ->select('client_ledger.*')
                        ->get();
        $all_cash_balances = array_pluck($cash_ledger, 'balance');
        $last_cash = last($all_cash_balances);

        $sales_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 14)
                        ->select('client_ledger.*')
                        ->get();

        $service_revenue_ledger =  DB::table('client_ledger')
                        ->where('client_ledger.business_id', '=', $businessInfo->id)
                        ->where('client_ledger.account_id', '=', 15)
                        ->select('client_ledger.*')
                        ->get();
        // return count($sales_revenue_ledger);
        if(count($sales_revenue_ledger) > 0)
        {
            $all_revenue_balances = array_pluck($sales_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);
        }
        else {
            $all_revenue_balances = array_pluck($service_revenue_ledger, 'balance');
            $last_revenue = last($all_revenue_balances);  
        }
        return view('dashboard.dashboard', compact('businesses', 'businessInfo','customers','items',
        'invoices','transactions','last_cash','last_revenue'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/modals/business_edit.blade.php
  <!--Edit Modal -->
  <div class="modal fade" id="editBusinessModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addModalLabel">
              Edit Business
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            @include('dashboard.forms.edit_business')
        </div>
      </div>
    </div>
  </div>
@if (count($errors) > 0)
      <script>
          $( document ).ready(function() {
              $('#editBusinessModal').modal('show');
          });
      </script>
@endif

<script>
    function showEditModal(business_id){
        var url = '{{ route("business.show", ["business"=> ":business"] ) }}';
        url = url.replace(':business', business_id);

        $('#editBusinessModal').modal('show');

        $.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				}	
			});
			$.ajax({
				url: url,
				method: "GET",
				success: function (data) {
          $('#editmodal').modal('show');
          $('#eid').val(data.id);
          $('#bname').val(data.name);
          $('#bphone').val(data.phone);
          $('#baddress').val(data.address);
          $('#bemail').val(data.email);
          $('#bwebsite').val(data.website);
				},
				error: function(err) {
					console.log(err);
				}
			})
    };
</script> 

resources/views/dashboard/modals/customer_edit.blade.php
  <!--Edit Modal -->
  <div class="modal fade" id="editCustomerModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addModalLabel">
              Edit Customer
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            @include('dashboard.forms.edit_customer')
        </div>
      </div>
    </div>
  </div>
@if (count($errors) > 0)
      <script>
          $( document ).ready(function() {
              $('#editCustomerModal').modal('show');
          });
      </script>
@endif

<script>
    function showEditModal(customer_id){
        var url = '{{ route("customers.show", ["businessCode" => $businessInfo->business_code, "customer"=> ":customer"] ) }}';
        url = url.replace(':customer', customer_id);

        $('#editCustomerModal').modal('show');

        $.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				}	
			});
			$.ajax({
				url: url,
				method: "GET",
				success: function (data) {
                    $('#e_bname').val(data.business_name);
                    $('#e_fname').val(data.first_name);
                    $('#e_lname').val(data.last_name);
                    $('#e_tel').val(data.tel);
                    $('#e_city').val(data.city);
                    $('#e_state').val(data.state);
                    $('#e_email').val(data.email);
                    $('#e_address').val(data.address);
                    $('#e_id').val(data.id);
				},
				error: function(err) {
					console.log(err);
				}
			})
    };
</script> 

resources/views/dashboard/modals/item_edit.blade.php
  <!--Edit Modal -->
  <div class="modal fade" id="editItemModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addModalLabel">
              Edit Item
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          @include('dashboard.forms.edit_item')
        </div>
      </div>
    </div>
  </div>
@if (count($errors) > 0)
      <script>
          $( document ).ready(function() {
              $('#editItemModal').modal('show');
          });
      </script>
@endif

<script>
    function showEditModal(item_id){
        var url = '{{ route("items.show", ["businessCode" => $businessInfo->business_code, "item"=> ":item"] ) }}';
        url = url.replace(':item', item_id);

        $('#editItemModal').modal('show');

        $.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				}	
			});
			$.ajax({
				url: url,
				method: "GET",
				success: function (data) {
          console.log(data)
          $('#e_id').val(data.id);
          $('#e_name').val(data.name);
          $('#e_type').val(data.type);
          $('#e_price').val(data.price);
          $('#e_account_name').val(data.account_name);
          $('#e_description').val(data.description);
          $('#e_unit').val(data.unit);
          if(data.type == 'Goods'){
            document.getElementById('e_goods').checked = true;
          }else {
            document.getElementById('e_service').checked = true;
          }
				},
				error: function(err) {
					console.log(err);
				}
			})
    };
</script> 

resources/views/dashboard/modals/subscribe.blade.php
<div class="modal fade" id="subscribeModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel">Select Subscription Plan</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           @if($plans->count() > 0)
          <div class="row">
            @foreach($plans as $plan)
              <div class="col-sm-6">
               @if($plan->plan == 'FREMIUM') 
                  <dl>
                    <dt>Starter</dt>
                      <dd>- Accounting Journal</dd>
                      <dd>- Invoice</dd>
                      <dd>- Downloading Disabled</dd>
                      <dd>- Printing Disabled</dd>
                  </dl> 
                  <form method="POST" action="{{ route('subscribe.store') }}">
                      @csrf
                  <input type="hidden" value="{{$plan->id}}" name="subscription_plan">
                  <button class="btn btn-sm btn-info" type="submit">
                       <i class="fa fa-credit-card-alt"></i> Try For Free</button>
                </form>
                  @else 
                    {{-- Enable monthly sub my commenting this form --}}
                    <dl>
                        <dt></dt>
                        <dt>Professional</dt>
                        <dd>- Accounting Journal</dd>
                        <dd>- Income Statement</dd>
                        <dd>- Balance Sheet</dd>
                        <dd>- Cash Flow Statement</dd>
                        <dd>- Invoice</dd>
                        <dd>- Downloading Enabled</dd>
                        <dd>- Printing Enabled</dd>
                    </dl>
                    <form method="POST" action="{{ route('pay') }}" accept-charset="UTF-8" class="form-horizontal" role="form" id="form_paystack">
                      <div class="row" style="margin-bottom:40px;">
                        <div class="col-md-8 col-md-offset-2">
                          @php
                            $value = $plan->amount * 100 ;
                          @endphp
                          <input type="hidden" name="email" value="{{auth()->user()->email}}"> 
                          <input type="hidden" name="orderID" value="{{$plan->id}}">
                          <input type="hidden" name="amount" value="{{$value}}" id="paystack_amount"> 
                          <input type="hidden" name="quantity" value="1">
                          @if(!Auth::guest())
                          <input type="hidden" name="metadata" value="{{ json_encode($array = ['user_id' => auth()->user()->id,'plan_id' => $plan->id, 'prev_url' => URL::current()]) }}" > 
                          @endif
                          <input type="hidden" name="reference" value="{{ Paystack::genTranxRef() }}"> 
                          <input type="hidden" name="key" value="{{ config('paystack.secretKey') }}"> 
                          {{ csrf_field() }} 
              
                          <input type="hidden" name="_token" value="{{ csrf_token() }}"> 
                          <p>
                            <button class="btn btn-info btn-sm" type="submit" value="Pay Now!" id="pay_btn">
                            <i class="fa fa-plus-circle fa-lg"></i> Pay Now!
                            </button>
                          </p>
                        </div>
                      </div>
                    </form>
                    {{-- End of montly sub form --}}
              @endif

            
              </div>
            @endforeach
          </div>
          @endif
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  @if (count($errors) > 0)
      <script>
          $( document ).ready(function() {
              $('#subscribeModal').modal('show');
          });
      </script>
  @endif

  <script>
    //  $(document).ready(function() { 
    //   $("#pay_btn").click(function(event) {
    //     event.preventDefault();
    //     console.log(111);
    //     $paystack_amount = $('#paystack_amount')
    //     const url = "{{ route('pay') }}";
    //     $('#form_paystack').attr('action', url);
    //   });
      //  button on click
      // check button price
      // if price isnt equal to the default price 
      // cut the code
      // submit code with jquery
    // })
  </script>

resources/views/dashboard/modals/upgrade.blade.php
<div class="modal fade" id="upgradeModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel">Upgrade Plan</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           @if(Session::get('plans')->count() > 0)
          <div class="row">
            <div class="col-sm-6">
              @foreach(Session::get('plans') as $plan)
               @if($plan->plan == 'PREMIUM') 
                  {{-- Enable monthly sub my commenting this form --}}
                  <dl>
                    <dt></dt>
                    <dt>Professional</dt>
                    <dd>- Accounting Journal</dd>
                    <dd>- Income Statement</dd>
                    <dd>- Balance Sheet</dd>
                    <dd>- Cash Flow Statement</dd>
                    <dd>- Invoice</dd>
                    <dd>- Downloading Enabled</dd>
                    <dd>- Printing Enabled</dd>
                </dl>
                <form method="POST" action="{{ route('pay') }}" accept-charset="UTF-8" class="form-horizontal" role="form">
                  <div class="row" style="margin-bottom:40px;">
                    <div class="col-md-8 col-md-offset-2">
                      @php
                        $value = $plan->amount * 100 ;
                      @endphp
                      <input type="hidden" name="email" value="{{auth()->user()->email}}"> 
                      <input type="hidden" name="orderID" value="{{$plan->id}}">
                      <input type="hidden" name="amount" value="{{$value}}" id="amount"> 
                      <input type="hidden" name="quantity" value="1">
                      @if(!Auth::guest())
                      <input type="hidden" name="metadata" value="{{ json_encode($array = ['user_id' => auth()->user()->id,'plan_id' => $plan->id, 'prev_url' => URL::current()]) }}" > 
                      @endif
                      <input type="hidden" name="reference" value="{{ Paystack::genTranxRef() }}"> 
                      <input type="hidden" name="key" value="{{ config('paystack.secretKey') }}"> 
                      {{ csrf_field() }} 
          
                      <input type="hidden" name="_token" value="{{ csrf_token() }}"> 
                      <p>
                        <button class="btn btn-info btn-sm" type="submit" value="Pay Now!">
                        <i class="fa fa-plus-circle fa-lg"></i> Pay Now!
                        </button>
                      </p>
                    </div>
                  </div>
                </form>
                {{-- End of montly sub form --}}
              @endif
              @endforeach

            
              </div>
            </div>
          @endif
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>